  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Power Platform CLI
      run: |
        npm install -g pac

    - name: Authenticate Power Platform (Target Environment)
      run: |
        pac auth create --url ${{ secrets.TARGET_ENV_URL }} --clientid ${{ secrets.CLIENT_ID }} --clientsecret ${{ secrets.CLIENT_SECRET }} --tenantid ${{ secrets.TENANT_ID }}

    - name: Import Solution to Target Environment
      run: |
        pac solution import --path ./solution.zip
      env:
        TARGET_ENV_URL: ${{ secrets.TARGET_ENV_URL }}
